name: CI
on:
    push:
        branches:
        - main
    schedule:
        - cron:  '17 3 * * 0'

jobs:

    typos:
        name: Typos
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   uses: crate-ci/typos@master
